{"name": "Verify that the order is not accepted if passing already processed order id.", "status": "passed", "description": "Verify that 404 code is returned for PUT request if passing already processed order id.", "steps": [{"name": "Accept order.", "status": "passed", "parameters": [{"name": "order_id", "value": "434505"}, {"name": "courier_id", "value": "488111"}], "start": 1742473784363, "stop": 1742473784771}], "start": 1742473784362, "stop": 1742473784772, "uuid": "709452dc-776e-4d0c-af74-acc3261d15f7", "historyId": "d1d566d844a7abeef7b8dc1c834facbb", "testCaseId": "d1d566d844a7abeef7b8dc1c834facbb", "fullName": "tests.test_order_accept.TestOrderAccept#test_accept_order_processed_order_not_accepted", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order_accept"}, {"name": "subSuite", "value": "TestOrderAccept"}, {"name": "host", "value": "ip-192-168-100-12.eu-north-1.compute.internal"}, {"name": "thread", "value": "48014-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order_accept"}]}