{"name": "Verify that the order is not accepted if passing already processed order id.", "status": "passed", "description": "Verify that 404 code is returned for PUT request if passing already processed order id.", "start": 1742244744096, "stop": 1742244744991, "uuid": "60674f5d-27e6-48a9-bcdc-03313bd66b77", "historyId": "160e26e3d49f6d399d11104181615736", "testCaseId": "160e26e3d49f6d399d11104181615736", "fullName": "tests.test_order.TestOrderAccept#test_accept_order_processed_order_not_accepted", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order"}, {"name": "subSuite", "value": "TestOrderAccept"}, {"name": "host", "value": "ip-192-168-100-6.eu-north-1.compute.internal"}, {"name": "thread", "value": "63648-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order"}]}